export const projectData: any = [
  {
    year: "2021",
    institute: "",
    title: "HRM Web Application",
    image: "/images/projects/hrm-1.png",
    video: "",
    images: [
      "/images/projects/hrm-2.png",
      "/images/projects/hrm-3.png",
      "/images/projects/hrm-4.png",
    ],
    link: "",
    linkTitle: "",
    details: [
      "Developed Drag and Drop canban feature",
      "Integrated Javascript charts and graphs",
      "Generated yearly and monthly report in excel and pdf format",
      "Developed multilevel user dashboard",
      "Provided API for android",
      "Secured users dashboard with OAuth2 authentication",
    ],
    github: "",
    status: "active",
    tech: ["Laravel", "Ajax", "Jquery", "MySQL"],
    about:
      "This project is a complete solution for any large scale industries Human Resource Management (HRM) ",
  },
  {
    year: "2023",
    institute: "Client Project",
    title: "LP Geobot",
    image: "/images/projects/lp-geobot.png",
    video: "",
    images: [],
    link: "https://lp-geobot.vercel.app/",
    linkTitle: "Site link",
    details: ["Figma to pixel perfect tailwind and next.js application"],
    github: "https://github.com/SmanSayeed/lp_geobot",
    status: "active",
    tech: ["next.js", "tailwind", "scss"],
    about:
      "Completed this project for a client. Implemented copy paste link feature and made this pixel perfect with tailwind css from figma",
  },
  {
    year: "2021",
    institute: "",
    title: "Multivendor Ecommerce",
    image: "",
    video: "",
    images: [],
    link: "",
    linkTitle: "",
    details: [
      "Integrated sslcommerze payment gateway",
      "Developed custom coupon code feature",
      "Created flash sale feature for a fixed time period",
      "Provided API for android",
      "Secured users and admin dashboard with OAuth2 authentication",
    ],
    github: "https://github.com/SmanSayeed/MongoDB-React-Node-MERN-CAR-SHOP",
    status: "",
    tech: ["react js", "node js"],
    about:
      "This project is a complete solution for any large scale industries Human Resource Management (HRM) ",
  },

  {
    year: "2021",
    institute: "",
    title: "Car Shop",
    image: "",
    video: "",
    images: [],
    link: "https://ph12-24d48.web.app/",
    linkTitle: "Site link",
    details: ["Developed food delivary web application with wordpress"],
    github: "https://github.com/SmanSayeed/MongoDB-React-Node-MERN-CAR-SHOP",
    status: "",
    tech: ["react js", "node js"],
    about:
      "This project helps managing customers, bank, products and making sales report of each customer with multiple products and generates sales report with pdf. The sales report can be changed easily by admin",
  },
  {
    year: "2018",
    institute: "Mensa Digiworld",
    title: "IMPORT EXPORT MANAGEMENT ",
    image: "/images/projects/import.png",
    video: "",
    images: [],
    link: "",
    linkTitle: "",
    details: ["Developed food delivary web application with wordpress"],
    github: "https://github.com/SmanSayeed/Import-Export-Company-ERP",
    status: "active",
    tech: ["php", "laravel", "ajax", "mysql"],
    about:
      "This project helps managing customers, bank, products and making sales report of each customer with multiple products and generates sales report with pdf. The sales report can be changed easily by admin",
  },
  {
    year: "2018",
    institute: "Roshodbari",
    title: "Online food delivery system",
    image: "",
    video: "",
    images: [],
    link: "https://roshodbari.com",
    linkTitle: "www.roshodbari.com",
    details: ["Developed food delivary web application with wordpress"],
    github: "",
    status: "",
    tech: ["wordpress"],
    about:
      "This project to select foods from different restaurent and order to admin. After ordering admin gets informed and process the order",
  },
  {
    year: "2019",
    institute: "",
    title: "Biometric POS system",
    image: "",
    video: "",
    images: [],
    link: "https://omsdebidwar.gov.bd",
    linkTitle: "www.omsdebidwar.gov.bd",
    details: [
      "Integrated Zkteco Fingerprint Device with laravel POS applicaiton",
      "Designed complex database management system",
      "Developed multiple user authentication",
    ],
    github: "",
    status: "",
    tech: ["laravel", "ajax", "mysql", "php", "Zktecho Fingerprint SDK"],
    about:
      "This application won Digital Bangladesh award 2020 to serve people of Cumilla District of Bangladesh by securing government cheap food delivery to poor people",
  },
  {
    year: "2019",
    institute: "Comilla University, Cumilla, Bangladesh",
    title: "Comilla University Convocation Payment",
    image: "",
    video: "",
    images: [],
    link: "",
    linkTitle: "",
    details: [
      "Integrated bkash payment gateway",
      "Secured students login and ID card generation after completing payment",
      "Developed admin panel to control all students data",
    ],
    github:
      "https://github.com/SmanSayeed/Convocation-Registration-And-Payment-with-Bkash",
    status: "",
    tech: ["laravel", "ajax", "mysql", "php"],

    about:
      "Developed this web application to maintain convocation payment system for 4000 students of Comilla University",
  },
];
